## Assembly constituency wise expenditure on MGNREGS in Balangir district of Orissa in 2019-20 through aggregation of Block level data

In [1]:
import sys
!{sys.executable} -m pip install openpyxl numpy pandas scikit-learn

Requirement already satisfied: openpyxl in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (3.0.7)
Requirement already satisfied: numpy in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (1.20.2)
Requirement already satisfied: pandas in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (1.2.4)
Requirement already satisfied: scikit-learn in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (0.24.1)
Requirement already satisfied: et-xmlfile in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (from openpyxl) (1.0.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (from scikit-learn) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (from scikit-learn) (1.0.1)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/Cellar/jupyterlab/3.0.13/libexec/lib/python3.9/site-packages (from scikit-learn) (1.6.2)

In [2]:
import openpyxl 
import pandas as pd
import numpy as np
import itertools
from openpyxl import load_workbook

In [3]:
district_level_file = "data/Civic Data Lab (updated).xlsx"
wb = load_workbook(filename=district_level_file)
ws = wb['Districts']

In [4]:
data = ws.values
cols = next(data)[:]
data = list(data)
#idx = [r[0] for r in data]
#data = (itertools.islice(r, 1, None) for r in data)

## Data Fields

The data file contains the following columns. 
1. **District** is the name of the district given in the provided [document](data/Odisha_MGNREGS_2019-20.xlsx) 
2. **District_Name** is the corresponding names of the districts as mentioned in Census of India, 2011
3. **Expenditure** is district-wise expenditure on MGNREGS in the year 2019-20
4. **Area_T** is the total area of the district as per the census of India, 2011 handbook of the state.
5. **Area_R** is the total rural area of the district as per the census of India, 2011 handbook of the state.
6. **Percent_HH_Rural** is the percentage of rural household with respect to the total household in the district.
7. **No_HH** is the total no. of households in the rural part of the district.
8. **TOT_P** is the total population in the rual area.
9. **P_06** is the population under 6 years of age.
10. **P_ILL** is the number of rural illiterate population in the district.
11. **TOT_WORK_P** is the total number of rural worker population i.e. no. of individuals who worked between 0 to 12 months in the reference year. It is the sum of Main Workers (who worked more than 6 months) and Marginal Worker (who worked less than 6 months).
12. **NON_WORK_P** is the total number of rural non worker population i.e. no. of individuals who didn't work in the reference year. 
13. **MARGWORK_P** is the number of rural marginal worker population i.e. no. of individuals who worked between 0 to 6 months in the reference year.
14. **MARGWORK_3_6_P** is the number of rural marginal worker population who worked between 3 to 6 months in the reference year.
15. **MARGWORK_0_3_P** is the number of rural marginal worker population who worked between 0 to 3 months in the reference year.

In [5]:
print(', '.join(cols))

SL. No., District, District_Name, Expenditure, Area_T, Area_R, Percent_HH_Rural, No_HH, TOT_P, P_06, P_ILL, TOT_WORK_P, NON_WORK_P, MARGWORK_P, MARGWORK_3_6_P, MARGWORK_0_3_P

In [6]:
dist_df = pd.DataFrame(data, columns=cols).infer_objects()

## Feature engineering
1. **AreaR/AreaT** is the ratio of rural area and total area. It is an important variable as MGNREGS is a scheme for rural employment and therefore the expenditure on the scheme is positively related to rural area in each district.
2. **MarWkP/TotWkP** is the ratio of total marginal workers and total work population. Total marginal worker is the number of individuals who worked less than 6 months in the reference period. Therefore, the the higer the number of marginal worker in a district, more will be the expenditure on MGNREGS. 
3. **NonWkP/TotWkP** is the ratio of non workers and workers. Total non worker is the number of individuals who didn't work in the previous year.

In [7]:
dist_df['AreaR/AreaT']= dist_df['Area_R']/dist_df['Area_T']

In [8]:
dist_df

,SL. No.,District,District_Name,Expenditure,Area_T,Area_R,Percent_HH_Rural,No_HH,TOT_P,P_06,P_ILL,TOT_WORK_P,NON_WORK_P,MARGWORK_P,MARGWORK_3_6_P,MARGWORK_0_3_P,AreaR/AreaT
0,1,ANGUL,Anugul,4738.38,6375.00,6198.12,0.840710,249733,1067275,130583,358206,455627,611648,198171,158371,39800,0.972254
1,2,BALESHWAR,Baleshwar,7689.49,3806.00,3675.32,0.890353,477434,2067236,260819,636895,847171,1220065,302716,227225,75491,0.965665
2,3,BARGARH,Bargarh,8666.33,5837.00,5759.09,0.895747,336130,1331145,146333,461973,706885,624260,280109,233403,46706,0.986652
3,4,BHADRAK,Bhadrak,4108.08,2505.00,2388.57,0.907704,270791,1320499,161574,355786,411154,909345,128740,104613,24127,0.953521
4,5,BOLANGIR,Balangir,14970.17,6575.00,6474.29,0.957377,369273,1451616,194634,670959,653289,798327,307264,248282,58982,0.984683
5,6,BOUDH,Baudh,3771.62,3098.00,3077.28,0.883976,102402,420738,59737,165022,212323,208415,94667,80518,14149,0.993312
6,7,CUTTACK,Cuttack,5089.70,3932.00,3703.07,0.741499,429454,1888423,201598,480445,683899,1204524,205250,163823,41427,0.941778
7,8,DEOGARH,Debagarh,3386.36,2940.00,2915.87,0.928511,70058,290130,37332,108830,157390,132740,80486,64637,15849,0.991793
8,9,DHENKANAL,Dhenkanal,9623.83,4452.00,4383.82,0.907225,253446,1075305,127334,339782,398386,676919,152607,125208,27399,0.984686
9,10,GAJAPATI,Gajapati,6327.98,4325.00,4287.95,0.874279,112365,507151,79684,293991,267265,239886,118144,98515,19629,0.991434
10,11,GANJAM,Ganjam,29142.19,8206.00,7846.32,0.786085,596062,2761030,342463,1125880,1231922,1529108,555034,459362,95672,0.956169
11,12,JAGATSINGHAPUR,Jagatsinghapur,2081.10,1668.00,1620.58,0.894067,233626,1020991,98291,222789,364377,656614,109149,92728,16421,0.971571
12,13,JAJPUR,Jajapur,5800.28,2899.00,2807.08,0.928391,378645,1692095,200284,503612,511605,1180490,139062,117326,21736,0.968293
13,14,JHARSUGUDA,Jharsuguda,3358.73,2114.00,1955.41,0.619479,84287,348340,37295,113378,169104,179236,65684,53836,11848,0.924981
14,15,KALAHANDI,Kalahandi,12073.21,7920.00,7865.31,0.930350,373304,1454882,208763,741120,709276,745606,367994,303702,64292,0.993095
15,16,KANDHAMAL,Kandhamal,11093.89,8021.00,7969.26,0.902536,155256,660831,101816,316938,329677,331154,183842,145407,38435,0.993549
16,17,KENDRAPARA,Kendrapara,5440.80,2644.00,2630.69,0.950095,305868,1356827,152138,333342,439698,917129,140509,114823,25686,0.994966
17,18,KENDUJHAR,Kendujhar,14760.01,8303.00,8101.03,0.859788,348448,1548674,224941,667985,682446,866228,313494,253801,59693,0.975675
18,19,KHORDHA,Khordha,2862.56,2813.00,2530.41,0.500401,247304,1167357,130977,307677,399642,767715,108017,89558,18459,0.899541
19,20,KORAPUT,Koraput,16789.15,8635.29,8807.00,0.837436,282783,1153478,199037,749053,610613,542865,287580,242744,44836,1.019885
20,21,MALKANGIRI,Malkangiri,4559.42,5791.00,5766.32,0.917340,126225,563664,102265,350783,291472,272192,128255,107995,20260,0.995738
21,22,MAYURBHANJ,Mayurbhanj,37590.17,10418.00,10309.93,0.925754,542726,2326842,332377,1106414,1156323,1170519,662964,528616,134348,0.989627
22,23,NABARANGAPUR,Nabarangapur,14694.33,5291.00,5218.69,0.926067,253208,1133321,197140,722786,577172,556149,322672,268879,53793,0.986333
23,24,NAYAGARH,Nayagarh,5596.71,3890.00,3835.36,0.923505,210850,883051,98936,257706,318229,564822,110228,89897,20331,0.985954
24,25,NUAPADA,Nuapada,5836.25,3852.00,3816.77,0.948026,144299,576328,84066,300464,292882,283446,151261,124801,26460,0.990854
25,26,PURI,Puri,5454.14,3479.00,3391.09,0.852748,313188,1433800,147983,351598,527927,905873,161345,131230,30115,0.974731
26,27,RAYAGADA,Rayagada,12618.64,7073.00,7004.34,0.847106,191568,820945,132230,515187,413699,407246,229832,198975,30857,0.990293
27,28,SAMBALPUR,Sambalpur,4790.50,6624.00,6467.75,0.718803,179411,733006,84408,262109,390542,342464,151753,127592,24161,0.976412
28,29,SONEPUR,Subarnapur,4423.18,2337.00,2284.21,0.921991,139346,560242,69350,198744,268217,292025,113048,95284,17764,0.977411
29,30,SUNDARGARH,Sundargarh,16370.73,9712.00,9436.12,0.652246,312497,1355340,181482,573193,625502,729838,309890,243106,66784,0.971594

In [9]:
dist_df['MarWkP/TotWkP']= dist_df['MARGWORK_P']/dist_df['TOT_WORK_P']

In [10]:
dist_df

,SL. No.,District,District_Name,Expenditure,Area_T,Area_R,Percent_HH_Rural,No_HH,TOT_P,P_06,P_ILL,TOT_WORK_P,NON_WORK_P,MARGWORK_P,MARGWORK_3_6_P,MARGWORK_0_3_P,AreaR/AreaT,MarWkP/TotWkP
0,1,ANGUL,Anugul,4738.38,6375.00,6198.12,0.840710,249733,1067275,130583,358206,455627,611648,198171,158371,39800,0.972254,0.434941
1,2,BALESHWAR,Baleshwar,7689.49,3806.00,3675.32,0.890353,477434,2067236,260819,636895,847171,1220065,302716,227225,75491,0.965665,0.357326
2,3,BARGARH,Bargarh,8666.33,5837.00,5759.09,0.895747,336130,1331145,146333,461973,706885,624260,280109,233403,46706,0.986652,0.396258
3,4,BHADRAK,Bhadrak,4108.08,2505.00,2388.57,0.907704,270791,1320499,161574,355786,411154,909345,128740,104613,24127,0.953521,0.313119
4,5,BOLANGIR,Balangir,14970.17,6575.00,6474.29,0.957377,369273,1451616,194634,670959,653289,798327,307264,248282,58982,0.984683,0.470334
5,6,BOUDH,Baudh,3771.62,3098.00,3077.28,0.883976,102402,420738,59737,165022,212323,208415,94667,80518,14149,0.993312,0.445863
6,7,CUTTACK,Cuttack,5089.70,3932.00,3703.07,0.741499,429454,1888423,201598,480445,683899,1204524,205250,163823,41427,0.941778,0.300117
7,8,DEOGARH,Debagarh,3386.36,2940.00,2915.87,0.928511,70058,290130,37332,108830,157390,132740,80486,64637,15849,0.991793,0.511379
8,9,DHENKANAL,Dhenkanal,9623.83,4452.00,4383.82,0.907225,253446,1075305,127334,339782,398386,676919,152607,125208,27399,0.984686,0.383063
9,10,GAJAPATI,Gajapati,6327.98,4325.00,4287.95,0.874279,112365,507151,79684,293991,267265,239886,118144,98515,19629,0.991434,0.442048
10,11,GANJAM,Ganjam,29142.19,8206.00,7846.32,0.786085,596062,2761030,342463,1125880,1231922,1529108,555034,459362,95672,0.956169,0.450543
11,12,JAGATSINGHAPUR,Jagatsinghapur,2081.10,1668.00,1620.58,0.894067,233626,1020991,98291,222789,364377,656614,109149,92728,16421,0.971571,0.299550
12,13,JAJPUR,Jajapur,5800.28,2899.00,2807.08,0.928391,378645,1692095,200284,503612,511605,1180490,139062,117326,21736,0.968293,0.271815
13,14,JHARSUGUDA,Jharsuguda,3358.73,2114.00,1955.41,0.619479,84287,348340,37295,113378,169104,179236,65684,53836,11848,0.924981,0.388424
14,15,KALAHANDI,Kalahandi,12073.21,7920.00,7865.31,0.930350,373304,1454882,208763,741120,709276,745606,367994,303702,64292,0.993095,0.518830
15,16,KANDHAMAL,Kandhamal,11093.89,8021.00,7969.26,0.902536,155256,660831,101816,316938,329677,331154,183842,145407,38435,0.993549,0.557643
16,17,KENDRAPARA,Kendrapara,5440.80,2644.00,2630.69,0.950095,305868,1356827,152138,333342,439698,917129,140509,114823,25686,0.994966,0.319558
17,18,KENDUJHAR,Kendujhar,14760.01,8303.00,8101.03,0.859788,348448,1548674,224941,667985,682446,866228,313494,253801,59693,0.975675,0.459368
18,19,KHORDHA,Khordha,2862.56,2813.00,2530.41,0.500401,247304,1167357,130977,307677,399642,767715,108017,89558,18459,0.899541,0.270284
19,20,KORAPUT,Koraput,16789.15,8635.29,8807.00,0.837436,282783,1153478,199037,749053,610613,542865,287580,242744,44836,1.019885,0.470969
20,21,MALKANGIRI,Malkangiri,4559.42,5791.00,5766.32,0.917340,126225,563664,102265,350783,291472,272192,128255,107995,20260,0.995738,0.440025
21,22,MAYURBHANJ,Mayurbhanj,37590.17,10418.00,10309.93,0.925754,542726,2326842,332377,1106414,1156323,1170519,662964,528616,134348,0.989627,0.573338
22,23,NABARANGAPUR,Nabarangapur,14694.33,5291.00,5218.69,0.926067,253208,1133321,197140,722786,577172,556149,322672,268879,53793,0.986333,0.559057
23,24,NAYAGARH,Nayagarh,5596.71,3890.00,3835.36,0.923505,210850,883051,98936,257706,318229,564822,110228,89897,20331,0.985954,0.346379
24,25,NUAPADA,Nuapada,5836.25,3852.00,3816.77,0.948026,144299,576328,84066,300464,292882,283446,151261,124801,26460,0.990854,0.516457
25,26,PURI,Puri,5454.14,3479.00,3391.09,0.852748,313188,1433800,147983,351598,527927,905873,161345,131230,30115,0.974731,0.305620
26,27,RAYAGADA,Rayagada,12618.64,7073.00,7004.34,0.847106,191568,820945,132230,515187,413699,407246,229832,198975,30857,0.990293,0.555554
27,28,SAMBALPUR,Sambalpur,4790.50,6624.00,6467.75,0.718803,179411,733006,84408,262109,390542,342464,151753,127592,24161,0.976412,0.388570
28,29,SONEPUR,Subarnapur,4423.18,2337.00,2284.21,0.921991,139346,560242,69350,198744,268217,292025,113048,95284,17764,0.977411,0.421480
29,30,SUNDARGARH,Sundargarh,16370.73,9712.00,9436.12,0.652246,312497,1355340,181482,573193,625502,729838,309890,243106,66784,0.971594,0.495426

In [11]:
dist_df['NonWkP/TotWkP']= dist_df['NON_WORK_P']/dist_df['TOT_WORK_P']

In [12]:
dist_df

,SL. No.,District,District_Name,Expenditure,Area_T,Area_R,Percent_HH_Rural,No_HH,TOT_P,P_06,P_ILL,TOT_WORK_P,NON_WORK_P,MARGWORK_P,MARGWORK_3_6_P,MARGWORK_0_3_P,AreaR/AreaT,MarWkP/TotWkP,NonWkP/TotWkP
0,1,ANGUL,Anugul,4738.38,6375.00,6198.12,0.840710,249733,1067275,130583,358206,455627,611648,198171,158371,39800,0.972254,0.434941,1.342431
1,2,BALESHWAR,Baleshwar,7689.49,3806.00,3675.32,0.890353,477434,2067236,260819,636895,847171,1220065,302716,227225,75491,0.965665,0.357326,1.440164
2,3,BARGARH,Bargarh,8666.33,5837.00,5759.09,0.895747,336130,1331145,146333,461973,706885,624260,280109,233403,46706,0.986652,0.396258,0.883114
3,4,BHADRAK,Bhadrak,4108.08,2505.00,2388.57,0.907704,270791,1320499,161574,355786,411154,909345,128740,104613,24127,0.953521,0.313119,2.211690
4,5,BOLANGIR,Balangir,14970.17,6575.00,6474.29,0.957377,369273,1451616,194634,670959,653289,798327,307264,248282,58982,0.984683,0.470334,1.222012
5,6,BOUDH,Baudh,3771.62,3098.00,3077.28,0.883976,102402,420738,59737,165022,212323,208415,94667,80518,14149,0.993312,0.445863,0.981594
6,7,CUTTACK,Cuttack,5089.70,3932.00,3703.07,0.741499,429454,1888423,201598,480445,683899,1204524,205250,163823,41427,0.941778,0.300117,1.761260
7,8,DEOGARH,Debagarh,3386.36,2940.00,2915.87,0.928511,70058,290130,37332,108830,157390,132740,80486,64637,15849,0.991793,0.511379,0.843383
8,9,DHENKANAL,Dhenkanal,9623.83,4452.00,4383.82,0.907225,253446,1075305,127334,339782,398386,676919,152607,125208,27399,0.984686,0.383063,1.699154
9,10,GAJAPATI,Gajapati,6327.98,4325.00,4287.95,0.874279,112365,507151,79684,293991,267265,239886,118144,98515,19629,0.991434,0.442048,0.897559
10,11,GANJAM,Ganjam,29142.19,8206.00,7846.32,0.786085,596062,2761030,342463,1125880,1231922,1529108,555034,459362,95672,0.956169,0.450543,1.241238
11,12,JAGATSINGHAPUR,Jagatsinghapur,2081.10,1668.00,1620.58,0.894067,233626,1020991,98291,222789,364377,656614,109149,92728,16421,0.971571,0.299550,1.802018
12,13,JAJPUR,Jajapur,5800.28,2899.00,2807.08,0.928391,378645,1692095,200284,503612,511605,1180490,139062,117326,21736,0.968293,0.271815,2.307425
13,14,JHARSUGUDA,Jharsuguda,3358.73,2114.00,1955.41,0.619479,84287,348340,37295,113378,169104,179236,65684,53836,11848,0.924981,0.388424,1.059916
14,15,KALAHANDI,Kalahandi,12073.21,7920.00,7865.31,0.930350,373304,1454882,208763,741120,709276,745606,367994,303702,64292,0.993095,0.518830,1.051221
15,16,KANDHAMAL,Kandhamal,11093.89,8021.00,7969.26,0.902536,155256,660831,101816,316938,329677,331154,183842,145407,38435,0.993549,0.557643,1.004480
16,17,KENDRAPARA,Kendrapara,5440.80,2644.00,2630.69,0.950095,305868,1356827,152138,333342,439698,917129,140509,114823,25686,0.994966,0.319558,2.085816
17,18,KENDUJHAR,Kendujhar,14760.01,8303.00,8101.03,0.859788,348448,1548674,224941,667985,682446,866228,313494,253801,59693,0.975675,0.459368,1.269299
18,19,KHORDHA,Khordha,2862.56,2813.00,2530.41,0.500401,247304,1167357,130977,307677,399642,767715,108017,89558,18459,0.899541,0.270284,1.921007
19,20,KORAPUT,Koraput,16789.15,8635.29,8807.00,0.837436,282783,1153478,199037,749053,610613,542865,287580,242744,44836,1.019885,0.470969,0.889049
20,21,MALKANGIRI,Malkangiri,4559.42,5791.00,5766.32,0.917340,126225,563664,102265,350783,291472,272192,128255,107995,20260,0.995738,0.440025,0.933853
21,22,MAYURBHANJ,Mayurbhanj,37590.17,10418.00,10309.93,0.925754,542726,2326842,332377,1106414,1156323,1170519,662964,528616,134348,0.989627,0.573338,1.012277
22,23,NABARANGAPUR,Nabarangapur,14694.33,5291.00,5218.69,0.926067,253208,1133321,197140,722786,577172,556149,322672,268879,53793,0.986333,0.559057,0.963576
23,24,NAYAGARH,Nayagarh,5596.71,3890.00,3835.36,0.923505,210850,883051,98936,257706,318229,564822,110228,89897,20331,0.985954,0.346379,1.774892
24,25,NUAPADA,Nuapada,5836.25,3852.00,3816.77,0.948026,144299,576328,84066,300464,292882,283446,151261,124801,26460,0.990854,0.516457,0.967782
25,26,PURI,Puri,5454.14,3479.00,3391.09,0.852748,313188,1433800,147983,351598,527927,905873,161345,131230,30115,0.974731,0.305620,1.715906
26,27,RAYAGADA,Rayagada,12618.64,7073.00,7004.34,0.847106,191568,820945,132230,515187,413699,407246,229832,198975,30857,0.990293,0.555554,0.984402
27,28,SAMBALPUR,Sambalpur,4790.50,6624.00,6467.75,0.718803,179411,733006,84408,262109,390542,342464,151753,127592,24161,0.976412,0.388570,0.876894
28,29,SONEPUR,Subarnapur,4423.18,2337.00,2284.21,0.921991,139346,560242,69350,198744,268217,292025,113048,95284,17764,0.977411,0.421480,1.088764
29,30,SUNDARGARH,Sundargarh,16370.73,9712.00,9436.12,0.652246,312497,1355340,181482,573193,625502,729838,309890,243106,66784,0.971594,0.495426,1.166804

In [13]:
dist_df

,SL. No.,District,District_Name,Expenditure,Area_T,Area_R,Percent_HH_Rural,No_HH,TOT_P,P_06,P_ILL,TOT_WORK_P,NON_WORK_P,MARGWORK_P,MARGWORK_3_6_P,MARGWORK_0_3_P,AreaR/AreaT,MarWkP/TotWkP,NonWkP/TotWkP
0,1,ANGUL,Anugul,4738.38,6375.00,6198.12,0.840710,249733,1067275,130583,358206,455627,611648,198171,158371,39800,0.972254,0.434941,1.342431
1,2,BALESHWAR,Baleshwar,7689.49,3806.00,3675.32,0.890353,477434,2067236,260819,636895,847171,1220065,302716,227225,75491,0.965665,0.357326,1.440164
2,3,BARGARH,Bargarh,8666.33,5837.00,5759.09,0.895747,336130,1331145,146333,461973,706885,624260,280109,233403,46706,0.986652,0.396258,0.883114
3,4,BHADRAK,Bhadrak,4108.08,2505.00,2388.57,0.907704,270791,1320499,161574,355786,411154,909345,128740,104613,24127,0.953521,0.313119,2.211690
4,5,BOLANGIR,Balangir,14970.17,6575.00,6474.29,0.957377,369273,1451616,194634,670959,653289,798327,307264,248282,58982,0.984683,0.470334,1.222012
5,6,BOUDH,Baudh,3771.62,3098.00,3077.28,0.883976,102402,420738,59737,165022,212323,208415,94667,80518,14149,0.993312,0.445863,0.981594
6,7,CUTTACK,Cuttack,5089.70,3932.00,3703.07,0.741499,429454,1888423,201598,480445,683899,1204524,205250,163823,41427,0.941778,0.300117,1.761260
7,8,DEOGARH,Debagarh,3386.36,2940.00,2915.87,0.928511,70058,290130,37332,108830,157390,132740,80486,64637,15849,0.991793,0.511379,0.843383
8,9,DHENKANAL,Dhenkanal,9623.83,4452.00,4383.82,0.907225,253446,1075305,127334,339782,398386,676919,152607,125208,27399,0.984686,0.383063,1.699154
9,10,GAJAPATI,Gajapati,6327.98,4325.00,4287.95,0.874279,112365,507151,79684,293991,267265,239886,118144,98515,19629,0.991434,0.442048,0.897559
10,11,GANJAM,Ganjam,29142.19,8206.00,7846.32,0.786085,596062,2761030,342463,1125880,1231922,1529108,555034,459362,95672,0.956169,0.450543,1.241238
11,12,JAGATSINGHAPUR,Jagatsinghapur,2081.10,1668.00,1620.58,0.894067,233626,1020991,98291,222789,364377,656614,109149,92728,16421,0.971571,0.299550,1.802018
12,13,JAJPUR,Jajapur,5800.28,2899.00,2807.08,0.928391,378645,1692095,200284,503612,511605,1180490,139062,117326,21736,0.968293,0.271815,2.307425
13,14,JHARSUGUDA,Jharsuguda,3358.73,2114.00,1955.41,0.619479,84287,348340,37295,113378,169104,179236,65684,53836,11848,0.924981,0.388424,1.059916
14,15,KALAHANDI,Kalahandi,12073.21,7920.00,7865.31,0.930350,373304,1454882,208763,741120,709276,745606,367994,303702,64292,0.993095,0.518830,1.051221
15,16,KANDHAMAL,Kandhamal,11093.89,8021.00,7969.26,0.902536,155256,660831,101816,316938,329677,331154,183842,145407,38435,0.993549,0.557643,1.004480
16,17,KENDRAPARA,Kendrapara,5440.80,2644.00,2630.69,0.950095,305868,1356827,152138,333342,439698,917129,140509,114823,25686,0.994966,0.319558,2.085816
17,18,KENDUJHAR,Kendujhar,14760.01,8303.00,8101.03,0.859788,348448,1548674,224941,667985,682446,866228,313494,253801,59693,0.975675,0.459368,1.269299
18,19,KHORDHA,Khordha,2862.56,2813.00,2530.41,0.500401,247304,1167357,130977,307677,399642,767715,108017,89558,18459,0.899541,0.270284,1.921007
19,20,KORAPUT,Koraput,16789.15,8635.29,8807.00,0.837436,282783,1153478,199037,749053,610613,542865,287580,242744,44836,1.019885,0.470969,0.889049
20,21,MALKANGIRI,Malkangiri,4559.42,5791.00,5766.32,0.917340,126225,563664,102265,350783,291472,272192,128255,107995,20260,0.995738,0.440025,0.933853
21,22,MAYURBHANJ,Mayurbhanj,37590.17,10418.00,10309.93,0.925754,542726,2326842,332377,1106414,1156323,1170519,662964,528616,134348,0.989627,0.573338,1.012277
22,23,NABARANGAPUR,Nabarangapur,14694.33,5291.00,5218.69,0.926067,253208,1133321,197140,722786,577172,556149,322672,268879,53793,0.986333,0.559057,0.963576
23,24,NAYAGARH,Nayagarh,5596.71,3890.00,3835.36,0.923505,210850,883051,98936,257706,318229,564822,110228,89897,20331,0.985954,0.346379,1.774892
24,25,NUAPADA,Nuapada,5836.25,3852.00,3816.77,0.948026,144299,576328,84066,300464,292882,283446,151261,124801,26460,0.990854,0.516457,0.967782
25,26,PURI,Puri,5454.14,3479.00,3391.09,0.852748,313188,1433800,147983,351598,527927,905873,161345,131230,30115,0.974731,0.305620,1.715906
26,27,RAYAGADA,Rayagada,12618.64,7073.00,7004.34,0.847106,191568,820945,132230,515187,413699,407246,229832,198975,30857,0.990293,0.555554,0.984402
27,28,SAMBALPUR,Sambalpur,4790.50,6624.00,6467.75,0.718803,179411,733006,84408,262109,390542,342464,151753,127592,24161,0.976412,0.388570,0.876894
28,29,SONEPUR,Subarnapur,4423.18,2337.00,2284.21,0.921991,139346,560242,69350,198744,268217,292025,113048,95284,17764,0.977411,0.421480,1.088764
29,30,SUNDARGARH,Sundargarh,16370.73,9712.00,9436.12,0.652246,312497,1355340,181482,573193,625502,729838,309890,243106,66784,0.971594,0.495426,1.166804

In [14]:
X = dist_df[['AreaR/AreaT','No_HH','TOT_P','P_ILL','MarWkP/TotWkP','NonWkP/TotWkP']]

In [15]:
Y = dist_df[['Expenditure']]

In [16]:
Y = dist_df[['Expenditure']]/dist_df[['Expenditure']].sum() #using ratio of expenditure

In [17]:
Y

    Expenditure
0      0.016702
1      0.027104
2      0.030547
3      0.014480
4      0.052766
5      0.013294
6      0.017940
7      0.011936
8      0.033922
9      0.022305
10     0.102719
11     0.007335
12     0.020445
13     0.011839
14     0.042555
15     0.039103
16     0.019177
17     0.052025
18     0.010090
19     0.059178
20     0.016071
21     0.132496
22     0.051794
23     0.019727
24     0.020571
25     0.019224
26     0.044478
27     0.016885
28     0.015591
29     0.057703

In [18]:
X

    AreaR/AreaT   No_HH    TOT_P    P_ILL  MarWkP/TotWkP  NonWkP/TotWkP
0      0.972254  249733  1067275   358206       0.434941       1.342431
1      0.965665  477434  2067236   636895       0.357326       1.440164
2      0.986652  336130  1331145   461973       0.396258       0.883114
3      0.953521  270791  1320499   355786       0.313119       2.211690
4      0.984683  369273  1451616   670959       0.470334       1.222012
5      0.993312  102402   420738   165022       0.445863       0.981594
6      0.941778  429454  1888423   480445       0.300117       1.761260
7      0.991793   70058   290130   108830       0.511379       0.843383
8      0.984686  253446  1075305   339782       0.383063       1.699154
9      0.991434  112365   507151   293991       0.442048       0.897559
10     0.956169  596062  2761030  1125880       0.450543       1.241238
11     0.971571  233626  1020991   222789       0.299550       1.802018
12     0.968293  378645  1692095   503612       0.271815       2.307425
13     0.924981   84287   348340   113378       0.388424       1.059916
14     0.993095  373304  1454882   741120       0.518830       1.051221
15     0.993549  155256   660831   316938       0.557643       1.004480
16     0.994966  305868  1356827   333342       0.319558       2.085816
17     0.975675  348448  1548674   667985       0.459368       1.269299
18     0.899541  247304  1167357   307677       0.270284       1.921007
19     1.019885  282783  1153478   749053       0.470969       0.889049
20     0.995738  126225   563664   350783       0.440025       0.933853
21     0.989627  542726  2326842  1106414       0.573338       1.012277
22     0.986333  253208  1133321   722786       0.559057       0.963576
23     0.985954  210850   883051   257706       0.346379       1.774892
24     0.990854  144299   576328   300464       0.516457       0.967782
25     0.974731  313188  1433800   351598       0.305620       1.715906
26     0.990293  191568   820945   515187       0.555554       0.984402
27     0.976412  179411   733006   262109       0.388570       0.876894
28     0.977411  139346   560242   198744       0.421480       1.088764
29     0.971594  312497  1355340   573193       0.495426       1.166804

## Regression Analysis

Linear regression regresses target variable over the whole range from $(-\infty, \infty)$. 
Also, expenditure for district has a higher upper bound than expenditure for AC.
To resolve these, expenditure is scaled to domain between 0 and 1 by taking its ratio over the whole. The expenditure ratio lies between 0 and 1 and used as Y. 

Next, the expenditure ratio as p is transformed back to the domain of $(-\infty, \infty)$ by taking log-odds :

$$ y = log(\frac{p}{1-p}) $$

Note, this transforms p to the domain of $(-\infty, \infty)$ at the values of 0 and 1 respectively. Now, we can use any regression technique, since our dependant variable ranges over whole real domain. But after regression prediction, the output should be transformed back to the domain of 0 to 1 by exponentiating the log-odds: 

$$ p = \frac{1}{e^{-y} + 1} $$

Note, this transforms y back to the domain of $(0, 1)$ at the values of $(-\infty, \infty)$ respectively.

For regressing x and y, we can choose any suitable regression techniques.
Over here, we have selected [Linear Regression](https://en.wikipedia.org/wiki/Linear_regression).

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler

class LogitRegression(LinearRegression):

    def fit(self, x, p):
        p = np.asarray(p)
        y = np.log(p / (1 - p))
        return super().fit(x, y)

    def predict(self, x):
        y = super().predict(x)
        return 1 / (np.exp(-y) + 1)


regr = LogitRegression()
regr.fit(X, Y)

LogitRegression()

In [20]:
regr.score(X,Y)

0.9322547036913506

In [21]:
# scaling for non-negative
regr_scaled = make_pipeline(MinMaxScaler(), LogitRegression())
regr_scaled.fit(X, Y)
regr_scaled.score(X,Y)

0.9322547036913506

In [22]:
AC_level_file = "data/Civic Data Lab (updated).xlsx"
wb = load_workbook(filename=AC_level_file)
ws = wb['ACs']

In [23]:
data = ws.values
cols = next(data)[:]
data = list(data)
#idx = [r[0] for r in data]
#data = (itertools.islice(r, 1, None) for r in data)

## Data Fields

The data file contains the following columns. 
1. **Assembly Constituency** is the name of the assembly constituencies in Balangir District.
2. **Blocks** is the name of the blocks in the respective assembly constituency.
3. **Total_Area** is the total area of the block as per the census of India, 2011 handbook of the state.
4. **Rural_Area** is the total rural area of the block as per the census of India, 2011 handbook of the state.
5. **No_HH** is the total no. of households in the rural part of the block.
6. **TOT_P** is the total population in the rual area.
7. **P_06** is the population under 6 years of age.
8. **P_ILL** is the number of rural illiterate population in the block.
9. **TOT_WORK_P** is the total number of rural worker population i.e. no. of individuals who worked between 0 to 12 months in the reference year. It is the sum of Main Workers (who worked more than 6 months) and Marginal Worker (who worked less than 6 months).
10. **NON_WORK_P** is the total number of rural non worker population i.e. no. of individuals who didn't work in the reference year. 
11. **MARGWORK_P** is the number of rural marginal worker population i.e. no. of individuals who worked between 0 to 6 months in the reference year.
12. **MARGWORK_3_6_P** is the number of rural marginal worker population who worked between 3 to 6 months in the reference year.
13. **MARGWORK_0_3_P** is the number of rural marginal worker population who worked between 0 to 3 months in the reference year.

In [24]:
print(', '.join(cols))

Assembly Constituency, Blocks, Total_Area, Rural_Area, N0_HH, TOT_P, P_06, P_ILL, TOT_WORK_P, NON_WORK_P, MARGWORK_P, MARGWORK_3_6_P, MARGWORK_0_3_P

In [25]:
ac_df = pd.DataFrame(data, columns=cols).infer_objects()

## Feature engineering
1. **AreaR/AreaT** is the ratio of rural area and total area. It is an important variable as MGNREGS is a scheme for rural employment and therefore the expenditure on the scheme is positively related to rural area in each district.
2. **MarWkP/TotWkP** is the ratio of total marginal workers and total work population. Total marginal worker is the number of individuals who worked less than 6 months in the reference period. Therefore, the the higer the number of marginal worker in a district, more will be the expenditure on MGNREGS. 
3. **NonWkP/TotWkP** is the ratio of non workers and workers. Total non worker is the number of individuals who didn't work in the previous year.

In [26]:
ac_df['AreaR/AreaT']= ac_df['Rural_Area']/ac_df['Total_Area']

In [27]:
ac_df['MarWkP/TotWkP']= ac_df['MARGWORK_P']/ac_df['TOT_WORK_P']

In [28]:
ac_df['NonWkP/TotWkP']= ac_df['NON_WORK_P']/ac_df['TOT_WORK_P']

In [29]:
ac_df

,Assembly Constituency,Blocks,Total_Area,Rural_Area,N0_HH,TOT_P,P_06,P_ILL,TOT_WORK_P,NON_WORK_P,MARGWORK_P,MARGWORK_3_6_P,MARGWORK_0_3_P,AreaR/AreaT,MarWkP/TotWkP,NonWkP/TotWkP
0,﻿TITLAGARH,Titilagarh,35109,35109,30879,118942,16530,58296,53531,65411,29651,22693,6958,1.000000,0.553903,1.221927
1,﻿TITLAGARH,Saintala,45443,45443,30899,114775,15095,50498,47173,67602,20341,16206,4135,1.000000,0.431200,1.433066
2,﻿TITLAGARH,Gudvella (Tentulikhunti),20550,20144,14935,57406,7657,24846,25478,31928,14043,12209,1834,0.980243,0.551181,1.253160
3,﻿PATNAGARH,Patnagarh,59145,59145,33388,130783,17036,57116,62448,68335,26066,19933,6133,1.000000,0.417403,1.094270
4,﻿PATNAGARH,Belpara,49917,49917,31759,128916,18666,67216,63019,65897,30433,25370,5063,1.000000,0.482918,1.045669
5,﻿PATNAGARH,Khaprakhol,44839,44839,24567,93557,12709,46495,44347,49210,20347,16885,3462,1.000000,0.458813,1.109658
6,﻿KANTABANJI,Turekela,33705,33705,21548,82781,12878,47903,38143,44638,18843,15664,3179,1.000000,0.494009,1.170280
7,﻿KANTABANJI,Bangomunda,31690,30588,26890,111330,15558,59765,55407,55923,29687,23793,5894,0.965226,0.535799,1.009313
8,﻿KANTABANJI,Muribahal,40273,40273,29389,114839,16303,60312,55275,59564,29284,24008,5276,1.000000,0.529787,1.077594
9,﻿LOISINGHA (SC),Loisingha,31760,31144,22691,89713,10817,35237,39773,49940,16278,12851,3427,0.980605,0.409273,1.255626
10,﻿LOISINGHA (SC),Puintala,34078,34078,26570,111635,14475,42942,46349,65286,16665,14001,2664,1.000000,0.359555,1.408574
11,﻿LOISINGHA (SC),Agalpur,29612,29612,25513,96342,10941,37100,43996,52346,20900,16417,4483,1.000000,0.475043,1.189790
12,﻿BOLANGIR,Balangir,38698,38698,25476,102952,13238,42767,41631,61321,15885,12599,3286,1.000000,0.381567,1.472965
13,﻿BOLANGIR,Deogaon,43201,43201,24769,97645,12731,40466,36719,60926,18841,15653,3188,1.000000,0.513113,1.659250

In [30]:
X = ac_df[['AreaR/AreaT','N0_HH','TOT_P','P_ILL','MarWkP/TotWkP','NonWkP/TotWkP']]

In [31]:
Y = regr.predict(X)

In [32]:
Y

array([[0.01788521],
       [0.01244868],
       [0.01567372],
       [0.01159511],
       [0.01432075],
       [0.01287303],
       [0.0144507 ],
       [0.01487382],
       [0.01636881],
       [0.01040397],
       [0.00979258],
       [0.01344428],
       [0.01055364],
       [0.01607824]])

In [33]:
Y = Y/sum(Y)

In [34]:
Y

array([[0.09375642],
       [0.06525746],
       [0.08216353],
       [0.06078293],
       [0.07507109],
       [0.06748197],
       [0.07575227],
       [0.07797032],
       [0.08580727],
       [0.05453887],
       [0.05133385],
       [0.07047654],
       [0.05532343],
       [0.08428406]])

In [35]:
sum(Y)* (dist_df.loc[(dist_df['District_Name'] == 'Balangir')]['Expenditure']).values[0] #14970.17

array([14970.17])

In [36]:
block_expenditure_df = pd.concat([ac_df['Blocks'], pd.DataFrame(Y * (dist_df.loc[(dist_df['District_Name'] == 'Balangir')]['Expenditure']).values[0], columns=["Expenditure"] )], axis=1)

In [37]:
block_expenditure_df

                      Blocks  Expenditure
0                 Titilagarh  1403.549481
1                   Saintala   976.915197
2   Gudvella (Tentulikhunti)  1230.002065
3                  Patnagarh   909.930732
4                    Belpara  1123.827031
5                 Khaprakhol  1010.216629
6                  Turekela   1134.024376
7                 Bangomunda  1167.228883
8                  Muribahal  1284.549367
9                  Loisingha   816.456170
10                  Puintala   768.476473
11                   Agalpur  1055.045732
12                  Balangir   828.201124
13                   Deogaon  1261.746742

In [38]:
AC_block_file = "data/Civic Data Lab (updated).xlsx"
wb = load_workbook(filename=AC_level_file)
ws = wb['AC_Block']

In [39]:
data = ws.values
cols = next(data)[:]
data = list(data)
#idx = [r[0] for r in data]
#data = (itertools.islice(r, 1, None) for r in data)

## Data Fields

The data file contains the following columns. 
1. **Assembly Constituency** is the name of the assembly constituencies in Balangir District.
2. **Blocks** is the name of the blocks in the respective assembly constituency.

In [40]:
print(', '.join(cols))

Assembly Constituency, Blocks

In [41]:
block_ac_df = pd.DataFrame(data, columns=cols).infer_objects()

In [42]:
Balangir_AC_df_concat = pd.merge(block_ac_df, block_expenditure_df, how="inner", on=["Blocks"])

In [43]:
Balangir_AC_df_concat

   Assembly Constituency                    Blocks  Expenditure
0             ﻿TITLAGARH                Titilagarh  1403.549481
1             ﻿TITLAGARH                  Saintala   976.915197
2             ﻿TITLAGARH  Gudvella (Tentulikhunti)  1230.002065
3             ﻿PATNAGARH                 Patnagarh   909.930732
4             ﻿PATNAGARH                   Belpara  1123.827031
5             ﻿PATNAGARH                Khaprakhol  1010.216629
6            ﻿KANTABANJI                 Turekela   1134.024376
7            ﻿KANTABANJI                Bangomunda  1167.228883
8            ﻿KANTABANJI                 Muribahal  1284.549367
9        ﻿LOISINGHA (SC)                 Loisingha   816.456170
10       ﻿LOISINGHA (SC)                  Puintala   768.476473
11       ﻿LOISINGHA (SC)                   Agalpur  1055.045732
12             ﻿BOLANGIR                  Balangir   828.201124
13             ﻿BOLANGIR                   Deogaon  1261.746742

In [44]:
Balangir_AC_df_concat.groupby(['Assembly Constituency']).sum(['Expenditure'])

#The sum of block level expenditure will as a result give the expenditure in respective assembly constituency

                       Expenditure
Assembly Constituency
﻿BOLANGIR              2089.947866
﻿KANTABANJI            3585.802626
﻿LOISINGHA (SC)        2639.978374
﻿PATNAGARH             3043.974391
﻿TITLAGARH             3610.466743

## The End